# This file is used by goreleaser / github actions to build the docker image.
# For local builds use Dockerfile
FROM alpine
COPY ./binance-proxy /go/bin/binance-proxy
EXPOSE 8090
EXPOSE 8091
ENTRYPOINT ["/go/bin/binance-proxy"]